version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg17
    container_name: iot_project_db_252
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: iot_main_db_252
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: